[[redirects]]
from = "/rest/*"
to = "https://ikryqjberxoyatgbxosk.supabase.co/rest/:splat"
status = 200
force = true

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, apikey, Authorization, Prefer"
